language: python
python:
    - "3.5"
install:
    - pip install .
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
script:
    - pylint -E groupcurses
    - cd groupcurses
    - py.test
after_success:
    - coveralls
